builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - 
    image_templates:
      - "jsleeio/{{ .ProjectName }}:{{ .Tag }}"
      - "jsleeio/{{ .ProjectName }}:v{{ .Major }}"
      - "jsleeio/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "jsleeio/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=PROJECT_NAME={{.ProjectName}}"
